# Generated by Django 3.0.8 on 2020-07-09 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField()),
                ('back', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('last_interaction_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('BTN', 'Button'), ('TXT', 'Text')], default='TXT', max_length=3)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='bot.Card')),
            ],
        ),
        migrations.CreateModel(
            name='LearningMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_title', models.CharField(max_length=255)),
                ('last_shown', models.DateTimeField()),
                ('show_after', models.DateTimeField()),
                ('show_count', models.IntegerField()),
                ('easy_count', models.IntegerField()),
                ('hard_count', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='bot.Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='bot.User')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='bot.Deck'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.NullBooleanField()),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='bot.Question')),
            ],
        ),
        migrations.AddIndex(
            model_name='learningmatrix',
            index=models.Index(fields=['user', 'card'], name='bot_learnin_user_id_80dd44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learningmatrix',
            unique_together={('user', 'card')},
        ),
    ]
