# Generated by Django 3.0.8 on 2020-07-14 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShownQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['title'], name='bot_deck_title_6324cc_idx'),
        ),
        migrations.AddField(
            model_name='shownquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='bot.Question'),
        ),
        migrations.AddField(
            model_name='shownquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.User'),
        ),
        migrations.AddIndex(
            model_name='shownquestion',
            index=models.Index(fields=['user', 'question'], name='bot_shownqu_user_id_f40a49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shownquestion',
            unique_together={('user', 'question')},
        ),
    ]
