# Generated by Django 3.0.8 on 2020-07-14 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20200714_1209'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shownquestion',
            name='bot_shownqu_user_id_f40a49_idx',
        ),
        migrations.AddField(
            model_name='shownquestion',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.Card'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='shownquestion',
            unique_together={('user', 'card')},
        ),
        migrations.AddIndex(
            model_name='shownquestion',
            index=models.Index(fields=['user', 'card'], name='bot_shownqu_user_id_9dd06e_idx'),
        ),
    ]
