# Generated by Django 3.0.8 on 2020-07-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20200714_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
