# Generated by Django 3.0.8 on 2020-07-17 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20200715_1715'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shownquestion',
            unique_together=set(),
        ),
    ]
