# Generated by Django 3.0.8 on 2020-07-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20200717_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='sound_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='sound_url',
            field=models.URLField(blank=True),
        ),
    ]
